name: Build

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Run Fake
      run: .\build.cmd -t BuildAction -p 4
      shell: cmd
      env:
        GitHubToken: ${{ secrets.GITHUB_TOKEN }}
