name: Release

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Run Fake
      run: .\build.cmd -t ReleaseAction
      shell: cmd
      env:
        GitHubToken: ${{ secrets.GITHUB_TOKEN }}
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
